# Generated by Django 6.0.3 on 2026-04-03 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_projectcategory_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_set', to='app.projectcategory', verbose_name='Project Category'),
        ),
    ]
